on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - ".github/**"

name: CI

jobs:
  analyze-test:
    name: Analyze and test
    uses: ./.github/workflows/analyze-test.yaml

  build:
    needs:
      - analyze-test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('**/pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path

      - name: Run prebuild
        run: bash prebuild.sh